drop SYNONYM USER001.SYN_PKG_APP_CREA_PEDIDO
/
drop SYNONYM USER001.SYN_TYRC_PERSON
/
drop SYNONYM USER001.SYN_TYRC_PED
/
drop SYNONYM USER001.SYN_TYTB_DET_PED
/
drop SYNONYM USER001.SYN_TYRC_DET_PED
/