
drop SEQUENCE USER001.SEQ_TIPO_IDENTIFICACION 
/
drop SEQUENCE USER001.SEQ_PERSONA 
/
drop SEQUENCE USER001.SEQ_PEDIDO 
/
drop SEQUENCE USER001.SEQ_ARTICULO 
/
drop SEQUENCE USER001.SEQ_DETALLE_PEDIDO 
/
