drop package USER001.PKG_DETALLE_PEDIDO
/
drop package USER001.PKG_ARTICULO
/
drop package USER001.PKG_PEDIDO
/
drop package USER001.PKG_PERSONA
/
drop package USER001.PKG_TIPO_IDENTIFICACION
/
drop package USER001.PKG_CLN_CREA_PEDIDO
/
drop package USER001.PKG_APP_CREA_PEDIDO
/
