/************************************************************************************
Descripción: Objeto de encargado de ...
Autor:       Nombre del desarrollador y usuario
Fecha:       01-01-2022
IdGestión:   Ticket-2132123
@copyright: NombreDeLaEmpresa
************************************************************************************/

create table USER001.TIPO_IDENTIFICACION 
(
ID_TIPO_IDENTIFICACION          NUMBER(4),
DESCRIPCION                     VARCHAR2(20)  NOT NULL,
ULTIMA_ACTUALIZACION            TIMESTAMP     NOT NULL
)
/
COMMENT ON TABLE USER001.TIPO_IDENTIFICACION IS 'TIPOS DE IDENTIFICACION EN EL PAIS' 
/
COMMENT ON COLUMN USER001.TIPO_IDENTIFICACION.ID_TIPO_IDENTIFICACION IS 'REPRESENTA EL IDENTIFICADOR DEL TIPO DE IDENTIFICACIÓN EN EL PAIS'
/
COMMENT ON COLUMN USER001.TIPO_IDENTIFICACION.DESCRIPCION IS 'REPRESENTA LA DESCRIPCION DEL TIPO DE IDENTIFICACIÓN EN EL PAIS'
/
COMMENT ON COLUMN USER001.TIPO_IDENTIFICACION.ULTIMA_ACTUALIZACION IS 'ULTIMA FECHA MODIFICACION/INSERCION DEL REGISTRO'
/